version: "3"
services:
  php:
    # build: .docker/php
    build: .
    container_name: "apache-srv"
    image: server-apache
    volumes:
      - .docker/apache/server.pem:/etc/ssl/certs/server.pem
      - .docker/apache/server-key.pem:/etc/ssl/private/server-key.pem
      - .docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - .:/var/www/html
    ports:
      - 8099:80
      - 4439:443
    restart: always
    networks:
      - network-app

networks:
  network-app:
    driver: bridge
